// 2 octaves: C4 to F5
export const NOTES = [
  { name: "C4",  freq: 261.63, isBlack: false, key: "a" },
  { name: "C#4", freq: 277.18, isBlack: true,  key: "w" },
  { name: "D4",  freq: 293.66, isBlack: false, key: "s" },
  { name: "D#4", freq: 311.13, isBlack: true,  key: "e" },
  { name: "E4",  freq: 329.63, isBlack: false, key: "d" },
  { name: "F4",  freq: 349.23, isBlack: false, key: "f" },
  { name: "F#4", freq: 369.99, isBlack: true,  key: "t" },
  { name: "G4",  freq: 392.00, isBlack: false, key: "g" },
  { name: "G#4", freq: 415.30, isBlack: true,  key: "y" },
  { name: "A4",  freq: 440.00, isBlack: false, key: "h" },
  { name: "A#4", freq: 466.16, isBlack: true,  key: "u" },
  { name: "B4",  freq: 493.88, isBlack: false, key: "j" },
  { name: "C5",  freq: 523.25, isBlack: false, key: "k" },
  { name: "C#5", freq: 554.37, isBlack: true,  key: "o" },
  { name: "D5",  freq: 587.33, isBlack: false, key: "l" },
  { name: "D#5", freq: 622.25, isBlack: true,  key: "p" },
  { name: "E5",  freq: 659.25, isBlack: false, key: ";" },
  { name: "F5",  freq: 698.46, isBlack: false, key: "'" },
];
